// Auto-generated from ingredients-with-possible-units.csv

export const INGREDIENTS = [
  'sugar free white chocolate pudding mix',
  'reduced fat and reduced sodium cream of mushroom soup',
  'reduced fat and reduced sodium cream of chicken soup',
  'reduced fat and reduced sodium cream of celery soup',
  'sugar free cheesecake pudding mix',
  'sugar free chocolate pudding mix',
  'sugar free vanilla pudding mix',
  'unsweetened dutch processed cocoa powder',
  'vanilla sandwich cookies',
  'allergy friendly chocolate chips',
  'dry roasted salted sunflower seeds',
  'low fat shredded mexican cheese blend',
  'boneless skinless chicken breast',
  'low moisture part skim mozzarella cheese',
  'sugar free raspberry gelatin',
  'boneless skinless chicken breast halves',
  'canned chipotle chiles in adobo',
  'gluten free chocolate sandwich cookies',
  'boneless skinless chicken thighs',
  'boneless skinless turkey breast',
  'textured vegetable protein',
  'low fat shredded mozzarella',
  'albacore tuna packed in oil',
  'boneless skin on chicken breast halves',
  'skinless chicken pieces',
  'hersheys kisses brand milk chocolates',
  'mini semisweet chocolate chips',
  'swerve confectioners',
  'powdered peanut butter with chocolate',
  'cooked whole wheat angel hair pasta',
  'roasted salted sunflower seeds',
  'gluten free vanilla sandwich cookies',
  'fat free chicken broth',
  'bone in skin on chicken breast halves',
  'reduced sodium cream of mushroom soup',
  'low fat sweetened condensed milk',
  'chicken leg quarters',
  'sugar free caramel sauce',
  'reduced fat string cheese',
  'butter flavored shortening',
  'unsweetened baking chocolate',
  'gluten free all purpose flour',
  'reduced sodium cream of chicken soup',
  'cranberry juice concentrate',
  'unsalted peanut butter',
  'low fat shredded cheddar',
  'cooked whole wheat farfalle',
  'anchovies in extra virgin olive oil',
  'chive and onion cream cheese spread',
  'gluten free refrigerated pie crusts',
  'bone in skin on turkey breast',
  'shichimi togarashi',
  'refrigerated crescent rolls',
  'gluten free elbow macaroni',
  'gluten free graham cracker squares',
  'dutch processed cocoa powder',
  'reduced fat cream of mushroom soup',
  'semisweet chocolate chips',
  'beef flavored ramen',
  'refrigerated dough sheet',
  'gluten free ladyfingers',
  'cola',
  'gluten free graham crackers',
  'garlic herb spreadable cheese',
  'reduced fat cream of chicken soup',
  'diced tomatoes with green chilies',
  'cooked instant brown rice',
  'chocolate covered sunflower seeds',
  'low fat graham crackers',
  'chocolate covered caramel candy',
  'sweetened condensed skim milk',
  'whole wheat crackers',
  'gluten free white sandwich bread',
  'lasagne noodles',
  'broccoli carrot cauliflower mix',
  'prepared whole wheat pizza crust',
  'country style beef ribs',
  'condensed cream of mushroom soup',
  'boneless skin on chicken breast',
  'reduced fat cream of celery soup',
  'pizza dough',
  'oil packed sun dried tomatoes',
  'chocolate covered espresso beans',
  'low fat greek yogurt',
  'vegetarian parmesan',
  'low fat vanilla greek yogurt',
  'solid white tuna packed in water',
  'fat free less sodium beef broth',
  'sugar cookie dough',
  'gluten free cheerios',
  'sardines in tomato sauce',
  'cooked short grain brown rice',
  'peanut butter candy',
  'bone in skin on chicken breast',
  'powdered sugar substitute',
  'bone in skinless chicken thighs',
  'ready to serve asian fried rice',
  'gluten free gingersnap cookies',
  'refrigerated spinach tortellini',
  'gluten free angel food cake mix',
  'chocolate graham cracker crumbs',
  'condensed cream of chicken soup',
  'sugar free strawberry preserves',
  'pickle juice',
  'lightly sweetened whipped cream',
  'reduced fat crescent rolls',
  'cooked whole wheat pasta shells',
  'boneless skin on chicken thighs',
  'gluten free shortbread cookies',
  'rotisserie chicken',
  'whole wheat angel hair pasta',
  'chocolate covered coffee beans',
  'colby jack',
  'boneless skin on turkey breast',
  'canned chipotle chile',
  'evaporated cane juice',
  'montreal steak seasoning',
  'boneless chicken breast halves',
  'instant cheesecake pudding mix',
  'sugar free raspberry preserves',
  'vegetarian chicken deli slices',
  'low sodium vegetable broth',
  '95 percent lean ground beef',
  'gluten free corn flakes',
  'bone in skin on chicken thighs',
  'strawberry flavored gelatin',
  'everything bagel seasoning',
  'condensed cream of celery soup',
  'raspberry flavored gelatin',
  'bone in skinless turkey breast',
  'fat free vanilla greek yogurt',
  'gluten free chocolate cake mix',
  'refrigerated cheese tortellini',
  '90 percent lean ground beef',
  'cooked hash browns',
  'roasted unsalted pumpkin seeds',
  'fresh flat leaf parsley',
  'shredded chicken',
  'whole wheat tortilla',
  'gluten free panko',
  'cupcakes',
  'chicken pieces',
  'ground chipotle chile pepper',
  'canned cannellini beans',
  'reduced fat mozzarella',
  'asian dressing',
  'italian seasoned breadcrumbs',
  'm&ms',
  'instant pistachio pudding mix',
  'pumpkin spice pudding mix',
  '93 percent lean ground turkey',
  'apple cider vinegar',
  'reduced fat chocolate milk',
  'candy coated chocolate pieces',
  'creme de menthe baking pieces',
  'orange juice concentrate',
  'whole wheat spaghetti',
  'butter flavored cooking spray',
  'balsamic vinaigrette',
  'bone in chicken breast halves',
  'italian turkey sausage',
  'gluten free funfetti cake mix',
  'dried chipotles',
  'gluten free frozen pie crust',
  'refrigerated pie crust',
  'instant chocolate pudding mix',
  'gluten free chocolate cookies',
  'reduced fat coleslaw dressing',
  'concentrated crushed tomatoes',
  'shredded mexican cheese blend',
  'dulce de leche',
  'low sodium chicken broth',
  'sugar free mini marshmallows',
  'pimento stuffed green olives',
  'cooked long grain white rice',
  'gluten free sugar cookie mix',
  'partially defatted soy flour',
  'unbleached all purpose flour',
  'farm raised catfish fillets',
  'gluten free vanilla cake mix',
  'artificial vanilla',
  'no salt added diced tomatoes',
  'cajun stewed tomatoes',
  'whole wheat farfalle',
  'roasted pumpkin seeds',
  'fire roasted tomatoes',
  'sugar free apricot preserves',
  'cooked gluten free spaghetti',
  'unseasoned rice vinegar',
  'nondairy butter',
  'gluten free macaroni',
  'lean strip steak',
  'ground all white meat turkey',
  'canned whole tomatoes',
  'chocolate digestive biscuits',
  'cooked long grain brown rice',
  'miniature peanut butter cups',
  'cooked whole wheat spaghetti',
  'unsweetened shredded coconut',
  'gluten free cornbread mix',
  'dried sweetened cranberries',
  '80 percent lean ground beef',
  'sugar free cherry preserves',
  'part skim mozzarella cheese',
  'sugar free strawberry jelly',
  'kosher dill sandwich slices',
  'chocolate sandwich cookies',
  'lemonade concentrate',
  'condensed french onion soup',
  'gluten free yellow cake mix',
  'whole wheat lasagne noodles',
  'expeller pressed canola oil',
  'canned great northern beans',
  'gluten free pizza dough mix',
  'reduced fat parmesan cheese',
  'sliced chicken breast',
  'fudge ice cream topping',
  'reduced fat evaporated milk',
  'skinless chicken drumsticks',
  'skinless rotisserie chicken',
  'no calorie sweetener packet',
  'cooked black lentils',
  'scotch bonnet chili',
  'cooked gluten free farfalle',
  'green hot sauce',
  'gluten free hamburger bun',
  'whole wheat hamburger bun',
  'unsalted sweet butter',
  'skim milk mozzarella',
  'skinless chicken leg',
  'dried red kidney beans',
  '85 percent lean ground beef',
  'instant vanilla pudding mix',
  'gluten free lasagne noodles',
  'whole cranberry sauce',
  'light chocolate ice cream',
  'amaranth flour',
  'cooked instant white rice',
  'vegetable oil cooking spray',
  'lemon',
  'bittersweet chocolate chips',
  'sweet potato vermicelli',
  'whole wheat english muffins',
  'aluminum free baking powder',
  'veggie sausage patties',
  'parmigiano reggiano',
  'gluten free white cake mix',
  'dried black lentils',
  'cooked pastina',
  'orange flavored gelatin',
  'whole wheat wrap',
  'sundried tomato wrap',
  'italian salad dressing mix',
  'cooked cellophane noodles',
  'sugar free chocolate syrup',
  'cooked short grain rice',
  'light salad dressing',
  'sunflower kernels',
  'low fat ricotta cheese',
  'cooked beef patties',
  'marinated artichoke hearts',
  'sugar free chocolate chips',
  'unsweetened coconut flakes',
  'sugar free pancake syrup',
  'whole wheat ravioli',
  'cooked whole wheat pasta',
  'smoked sausage',
  'crushed shortbread cookies',
  'oven ready lasagne noodles',
  'cooked orecchiette',
  'lean ground beef',
  'whole wheat elbow macaroni',
  'low carb tortilla',
  'chicken tenderloins',
  'cooked gluten free fusili',
  'sesame seed burger bun',
  'cooked quick cooking grits',
  'butter lettuce leaves',
  'cooked mostaccioli',
  'sugar free blueberry jelly',
  'extra sharp cheddar cheese',
  'seasoned rice vinegar',
  'clabber girl baking powder',
  'dried great northern beans',
  'reduced sodium tomato soup',
  'canned green chiles',
  'strawberry jello',
  'vegetable shortening',
  'frozen low fat waffles',
  'low fat vanilla yogurt',
  'chocolate crumb crust',
  'shredded mozzarella',
  'sugar free raspberry jelly',
  'limeade concentrate',
  'cooked medium grain rice',
  'light asian dressing',
  'red skinned sweet potato',
  'bone in bison short ribs',
  'buttermilk biscuits',
  'macaroni and cheese',
  'tri color tortilla chipps',
  'hamburger bun',
  'vinaigrette',
  'low fat cottage cheese',
  'cherry flavored gelatin',
  'chicken drumsticks',
  'aged balsamic vinegar',
  'cooked gluten free pasta',
  'sugar free syrup',
  'sweetened shredded coconut',
  'dried arbol chile',
  'fat free greek yogurt',
  'cooked angel hair pasta',
  'cooked spinach tortellini',
  'blanched slivered almonds',
  'pickled jalapenos',
  'yellow miso',
  'thai chili',
  'low fat chocolate milk',
  'fat free parmesan cheese',
  'chicken bouillon granules',
  'bison sirloin tip roast',
  'whole grain dijon mustard',
  'whole wheat hot dog bun',
  'turkey tenderloin',
  'gluten free fusili',
  'vegan buttery spread',
  'sweet butter',
  'cooked quinoa',
  'quick cooking oats',
  'reduced fat cream cheese',
  'mini chocolate chips',
  'reduced fat creme fraiche',
  'dark chocolate bar',
  'diced green chiles',
  'whole wheat penne',
  'dark chocolate couverture',
  'cooked rolled oats',
  'instant lemon pudding mix',
  'american cheese',
  'light vanilla ice cream',
  'chocolate hazelnut spread',
  'cocktail turkey sausages',
  'any color food color',
  'caramel sauce',
  'whole wheat fusilli',
  'reduced fat peanut butter',
  'sausage patties',
  'splenda brown sugar blend',
  'chinese five spice',
  'canned white kidney beans',
  'chocolate covered raisins',
  'cooked udon noodles',
  'cooked quick cooking oats',
  'low fat half and half',
  'rolled oats',
  'ice cream sandwiches',
  'cooked jumbo pasta shells',
  'sugar free blackberry jam',
  'sugar free strawberry jam',
  'curly leaf lettuce leaves',
  'pineapple chunks',
  'freeze dried strawberries',
  'unsweetened coconut',
  'silver tequila',
  'low sodium beef broth',
  'lemon flavored gelatin',
  'maraschino liqueur',
  'gluten free hot dog bun',
  'queso fresco',
  'artichoke hearts',
  'dry ranch dressing mix',
  'sugar free raspberry jam',
  'gluten free french bread',
  'instant white rice',
  'butter crackers',
  'whipped cream stabilizer',
  'peanut butter cookie mix',
  'dried cannellini beans',
  'fat free vanilla yogurt',
  'portobello mushroom caps',
  'haricots verts',
  'light coconut milk',
  'lower sodium soy sauce',
  'cooked farfalle',
  'vital wheat gluten',
  'gluten free pie dough',
  'cherry tomato',
  'cooked yellow split peas',
  'dried shiitake mushrooms',
  'thousand island dressing',
  'real bacon pieces',
  'nonfat plain yogurt',
  'red bean paste',
  'sweetened coconut flakes',
  'reduced fat swiss cheese',
  'korean bbq marinade',
  'fat free ricotta cheese',
  'instant brown rice',
  'white miso',
  'peppermint crunch',
  'low sodium baking powder',
  'gluten free stuffing mix',
  'whole wheat breadcrumbs',
  'dried spinach tortellini',
  'graham cracker pie crust',
  'fiori di sicilia',
  'string cheese',
  'red flesh navel orange',
  'nutritional yeast flakes',
  'mandarin orange sections',
  'unsweetened cocoa powder',
  'crispy chow mein noodles',
  'fat free whipped topping',
  'whole wheat pasta shells',
  'sazon completa',
  'flat leaf parsley',
  'dried white kidney beans',
  'vegetable bouillon cube',
  'cranberry juice cocktail',
  'boneless beef short ribs',
  'veggie burger',
  'whole wheat pastry flour',
  'sliced swiss cheese',
  'cooked chow mein noodles',
  'aji amarillo chili paste',
  'chocolate protein powder',
  'gluten free breadcrumbs',
  'shiitake mushrooms',
  'unsweetened coconut milk',
  'risotto rice',
  'angel food cake',
  'boneless pork loin',
  'sweetened condensed milk',
  'block style cream cheese',
  'low fat plain yogurt',
  'cooked cheese tortellini',
  'jerk seasoning',
  'ribeye steak',
  '1 percent chocolate milk',
  'low sodium chicken stock',
  'brown rice pasta',
  'lime flavored gelatin',
  'mackerel fillets',
  'teriyaki sauce',
  'butterscotch pudding mix',
  'roasted red peppers',
  'sugar free blueberry jam',
  'short grain brown rice',
  'milky way',
  'bocconcini',
  'fresh mozzarella',
  'olive oil spray',
  'dried cheese tortellini',
  'chipotle pepper flakes',
  'distilled white vinegar',
  'boneless pork rib roast',
  'whole grain spelt flour',
  'maraschino cherry syrup',
  'country style pork ribs',
  'light buttery spread',
  'chocolate chip cookies',
  'mixed mushrooms',
  'instant espresso',
  'canned diced tomatoes',
  'sugar free marshmallows',
  'egg replacer',
  'whole wheat chex',
  'canned red kidney beans',
  'red leaf lettuce leaves',
  'chickpea rotini',
  'dried porcini mushrooms',
  'red pepper flakes',
  'chocolate milk',
  'finely grated lime zest',
  'boneless chicken breast',
  'peppermint candy',
  'frozen artichoke hearts',
  'creme de menthe',
  'veggie crumbles',
  'hungarian sweet paprika',
  'sweetened coconut',
  'urad dal',
  'shredded wheat cereal',
  'italian seasoning',
  'seasoned soybean paste',
  'oreo cookies',
  'applesauce',
  'fat free cottage cheese',
  'gluten free flour mix',
  'turkey pepperoni',
  'chocolate wafer cookies',
  'quesadilla cheese',
  'gochugaru',
  'refrigerated tortellini',
  'bourbon vanilla extract',
  'cooked macaroni',
  'cottage cheese',
  'lean lamb loin chop',
  'gummy worms',
  'strawberry jam',
  'canned mandarin oranges',
  'gluten free pancake mix',
  'gluten free pizza dough',
  'sweetened whipped cream',
  'chipotle chiles',
  'bratwurst',
  'plain yogurt',
  'shredded cheddar cheese',
  'boneless chicken thighs',
  'ras el hanout',
  'soy lecithin granules',
  'coffee liqueur',
  'cooked israeli couscous',
  'homemade granola',
  'canned baby limas beans',
  'lean bone in pork chop',
  'chicken bouillon powder',
  'canned peas and carrots',
  'yellow split peas',
  'gluten free bread flour',
  'whole wheat pita',
  'instant potatoes flakes',
  'reduced fat feta cheese',
  'pie crust',
  'yellow mustard',
  'high gluten flour',
  'tennessee honey',
  'finely crushed pretzels',
  'catalina dressing',
  'chicken bratwurst',
  'bone in beef short ribs',
  'cooked wide egg noodles',
  'bakers white chocolate',
  'whole wheat pizza dough',
  'poultry seasoning',
  'moong dal',
  'boneless turkey breast',
  'white chocolate chips',
  'sun dried tomatoes',
  'whole wheat flour',
  'provolone cheese slices',
  'cooked chicken breast',
  'carrot leaves',
  'no calorie sweetener',
  'fat free cheddar cheese',
  'bone in pork loin',
  'black peppercorns',
  'mixed vegetables',
  'white whole wheat flour',
  'cooked bucatini',
  'instant coffee',
  'sub bun',
  'cooked anellini pasta',
  'hot fudge sauce',
  'evaporated milk',
  'chickpea elbow macaroni',
  'gluten free brownie mix',
  'nutritional yeast',
  'salted roasted cashews',
  'german sweet chocolate',
  'grated parmesan cheese',
  'frozen baby lima beans',
  'turkey burgers',
  'carrot quickbread mix',
  'fresh cilantro',
  'powdered peanut butter',
  'asian vegetables',
  'cooked rice vermicelli',
  'turkey bratwurst',
  'cooked long grain rice',
  'coconut extract',
  'refrigerated pie dough',
  'imitation lobster',
  'italian toast crackers',
  'chicken bouillon cube',
  'butterfinger candy bar',
  'banana bread mix',
  'vanilla protein powder',
  'bone in chicken thighs',
  'split peas',
  'pink himalayan salt',
  'prepared polenta',
  'vegetarian baked beans',
  'sliced roast beef',
  'pimento cheese',
  'golden delicious apple',
  'white asparagus',
  'beef bouillon cube',
  'italian dressing',
  'wheat bran',
  'fat free half and half',
  'nonfat dry milk powder',
  'boneless chicken wings',
  'cinnamon bagels',
  'cream of mushroom soup',
  'strawberry pie filling',
  'sundried tomato paste',
  'low sugar ketchup',
  'boneless pork shoulder',
  'low fat buttermilk',
  'red miso',
  'beef sirloin tip roast',
  'gluten free croissant',
  'serrano pepper',
  'granulated lemon sugar',
  'pickled mustard greens',
  'arrowroot',
  'buttery round crackers',
  'barbecue sauce',
  'gluten free muffin mix',
  'ground turkey',
  'dried fenugreek leaves',
  'bone in chicken breast',
  'amaretti cookie crumbs',
  'shoulder joint of pork',
  'orange jello',
  'gluten free baking mix',
  'white button mushrooms',
  'top sirloin steak',
  'bittersweet chocolate',
  'gluten free pie crust',
  'chinese cabbage',
  'coconut creamer',
  'granulated sugar',
  'extra virgin olive oil',
  'skim milk quark',
  'pork sirloin tip roast',
  'mini marshmallows',
  'unbleached flour',
  'canned water chestnuts',
  'sugar free apricot jam',
  'coconut pecan frosting',
  'lemon pepper',
  'canned cranberry beans',
  'microwave popcorn',
  'bread flour',
  'hot giardiniera',
  'romaine',
  'romanesco',
  'cooked corkscrew pasta',
  'tomato and basil sauce',
  'snickers bar',
  'ciabatta sandwich roll',
  'canned blackeyed peas',
  'anchovies in olive oil',
  'sugar free grape jelly',
  'fresh fenugreek leaves',
  'tenderloin steak',
  'light mayonnaise',
  'allspice berries',
  'hot chocolate',
  'veggie deli slices',
  'chocolate wafer crumbs',
  'graham cracker squares',
  'salted peanuts',
  'dried hibiscus',
  'marmite',
  'king trumpet mushrooms',
  'sundried tomato pesto',
  'hot cocoa mix',
  'burrito size tortilla',
  'pecorino romano',
  'champagne vinegar',
  'beef bouillon granules',
  'oil cured black olives',
  'bone in pork rib roast',
  'dried cilantro',
  'teff flour',
  'applewood smoked bacon',
  'white balsamic vinegar',
  'dark chocolate chips',
  'milk chocolate chips',
  'hamburger helper',
  'cooked lasagne noodles',
  'cooked cavatappi',
  'iceburg lettuce leaves',
  'light sour cream',
  'canned anchovies',
  'yellow cherry tomato',
  'ground coriander',
  'coconut milk beverage',
  'rainbow trout fillets',
  'french fries',
  'fresh tarragon',
  'red kidney beans',
  'chicken sausage',
  'pepper and onion mix',
  'graham cracker crumbs',
  'shelled edamame',
  'lemon jello',
  'crunchy peanut butter',
  'baked tortilla chips',
  'cooked pearl barley',
  'vine ripened tomatoes',
  'gluten free spaghetti',
  'oat flour',
  'long grain white rice',
  'captain crunch',
  'bone in turkey breast',
  'pico piquin seasoning',
  'braggs liquid aminos',
  'cooked elbow macaroni',
  'orange food color',
  'light ice cream',
  'vegetable oil',
  'chocolate mint',
  'italian sausage',
  'cheez whiz',
  'sweet dumpling squash',
  'cinnamon sugar butter',
  'condensed tomato soup',
  'pork shoulder',
  'lean pork loin chops',
  'cooked farfalle tonde',
  'fat free cream cheese',
  'lean pork tenderloin',
  'half and half',
  'sweet italian sausage',
  'sugar free cherry jam',
  'swerve',
  'yellow food color',
  'chicken thigh fillets',
  'sunflower seed butter',
  'orange extract',
  'broccoli coleslaw mix',
  'jaegermeister',
  'fresh rosemary',
  'wild boar tenderloins',
  'raspberry vinaigrette',
  'peanut sauce',
  'dried blackeyed peas',
  'chocolate cupcake mix',
  'panko',
  'schisandra berries',
  'mozzarella',
  'cooked kamut',
  'buffalo sauce',
  'egg substitute',
  'canned gigante beans',
  'cream of chicken soup',
  'cooked glutinous rice',
  'gluten free tortilla',
  'waffle cone',
  'graham crackers',
  'chocolate soy pudding',
  'dried rosemary',
  'defatted peanut flour',
  'long grain brown rice',
  'douchi',
  'blueberry pie filling',
  'coarse grain mustard',
  'ground beef',
  'chocolate milk powder',
  'canned chicken breast',
  'calumet baking powder',
  'seedless green grapes',
  'coconut milk',
  'light muscovado sugar',
  'chicken breast halves',
  'vanilla wafer cookies',
  'sweet corn on the cob',
  'chocolate eggs',
  'table syrup',
  'ladyfingers',
  'salt and pepper',
  'cauliflower florets',
  'chili powder',
  'cocoa krispies cereal',
  'ricotta salata cheese',
  'nacho cheese doritos',
  'cream cheese frosting',
  'scoops tortilla chips',
  'seasoned breadcrumbs',
  'carbiquick',
  'petite tomatoes',
  'lions mane mushrooms',
  'whole coriander seeds',
  'dried baby lima beans',
  'dill pickle slices',
  'blanched almond flour',
  'ramen noodles',
  'ground cayenne pepper',
  'fernet branca',
  'dried cranberry beans',
  'chocolate malt powder',
  'chanterelle mushrooms',
  'chicken wings',
  'pretzel roll',
  'salt packed anchovies',
  'chipotle chile puree',
  'lean bacon',
  'caesar salad dressing',
  'green enchilada sauce',
  'tahitian vanilla bean',
  'frosted flakes',
  'quick cooking tapioca',
  'devils food cake mix',
  'bison sirloin',
  'vanilla frozen yogurt',
  'nutter butter cookies',
  'horseradish sauce',
  'fruity pebbles cereal',
  'cooked steel cut oats',
  'fruit pectin',
  'hash browns',
  'canned borlotti beans',
  'bacon ends and pieces',
  'turkey breast cutlets',
  'straw mushrooms',
  'greek yogurt',
  'hollandaise sauce mix',
  'raisin bread',
  'bison ribeye',
  'canned chickpeas',
  'coconut sugar',
  'margarine',
  'chicken stock powder',
  'fresh lasagne sheets',
  'full bodied red wine',
  'white sandwich bread',
  'mini rice cakes',
  'blackening spice',
  'cooked wheatberries',
  'dried cherries',
  'creamy peanut butter',
  'green cardamoms',
  'canned pumpkin',
  'ham slices',
  'sprouted grain bread',
  'vanilla extract',
  'red leicester',
  'leftover turkey',
  'boneless chuck steak',
  'monk fruit extract',
  'durum flour',
  'grissini',
  'yellow squash',
  'ground chorizo',
  'ricotta cheese',
  'whole wheat pretzels',
  'crimini mushrooms',
  'heavy cream',
  'cooked arborrio rice',
  'yellowtail snapper',
  'chili without beans',
  'cooked green lentils',
  'edamame in the pod',
  'dark muscovado sugar',
  'strip steak',
  'sriracha',
  'unsulfured molasses',
  'dried chickpeas',
  'lime jello',
  'tuna packed in water',
  'cooked ramen noodles',
  'sliced turkey',
  'vegan protein powder',
  'sugar free preserves',
  'savoy cabbage leaves',
  'whipped butter',
  'butterscotch pudding',
  'sugar free grape jam',
  'meyer lemon juice',
  'strawberry preserves',
  'tapioca starch',
  'unsweetened soymilk',
  'blue cheese crumbles',
  'rice krispies cereal',
  'yellow pepper',
  'cooked brown lentils',
  'long sweet pepper',
  'thai red curry paste',
  'beef bouillon powder',
  'veggie meatballs',
  'white corn tortilla',
  'red cinnamon candy',
  'ranch dressing',
  'cooked fusilli',
  'canned albacore tuna',
  'white cheddar cheese',
  'peperoncini',
  'white cheese dip',
  'collagen powder',
  'apricot pie filling',
  'almond joy bar',
  'canadian bacon',
  'orange pepper',
  'great northern beans',
  'white sweet potato',
  'green food color',
  'prepared pizza crust',
  'midori melon liqueur',
  'semisweet chocolate',
  'strong coffee',
  'seasoning',
  'jerusalem artichoke',
  'black lentils',
  'italian cheese',
  'deep dish pie crust',
  'pineapple with juice',
  'canned boysenberries',
  'black cardamoms',
  'psyllium seed powder',
  'corn flake crumbs',
  'spring roll wrappers',
  'cooked instant grits',
  'vegetable tortellini',
  'yellow mustard seeds',
  'cauliflower rice',
  'worcestershire sauce',
  'green chili pepper',
  'flour tortilla',
  'orange flower water',
  'buffalo mozzarella',
  'portobello mushrooms',
  'psyllium husk powder',
  'pomegranate molasses',
  'fat free feta cheese',
  'whole wheat couscous',
  'dried parsley',
  'dry israeli couscous',
  'gluten free pretzels',
  'black beans',
  'dumpling wrappers',
  'red delicious apple',
  'dried gigante beans',
  'cream of celery soup',
  'quick cooking barley',
  'filo pastry',
  'vegan buttery stick',
  'chicken fat',
  'red jalapeno',
  'jarred sour cherries',
  'fresh cayenne pepper',
  'red potato',
  'yellow passion fruit',
  'whole grain tortilla',
  'strawberry ice cream',
  'pomegranate seeds',
  'marinated artichokes',
  'low sodium broth',
  'tamarind paste',
  'fresh parsley',
  'vegan cheddar cheese',
  'grapefruit juice',
  'arbol chile',
  'dried borlotti beans',
  'cocoa pebbles cereal',
  'chana dal',
  'fresh oregano',
  'monterey jack cheese',
  'cream of potato soup',
  'powdered sugar',
  'tartlet shells',
  'candy melts',
  'canned smoked salmon',
  'corn tortilla chips',
  'dried chili pepper',
  'gluten free crackers',
  'stone ground mustard',
  'veggie sausage',
  'evaporated skim milk',
  'in shell walnuts',
  'ancho chili pepper',
  'blue cheese dressing',
  'sharp cheddar cheese',
  'hawaiian roll',
  'malted milk balls',
  'gluten free farfalle',
  'chili seasoning mix',
  'apple butter',
  'ginger garlic paste',
  'crescent roll dough',
  'fat free mayonnaise',
  'shirataki pasta',
  'alfredo sauce',
  'miracle whip',
  'peanut butter chips',
  'sweet potato leaves',
  'canned kidney beans',
  'grana padano',
  'low fat yogurt',
  'red enchilada sauce',
  'red velvet cake mix',
  'cellophane noodles',
  'pulled pork',
  'spicy brown mustard',
  'halloween sprinkles',
  'canned butter beans',
  'boursin cheese',
  'almond extract',
  'chopped dried pears',
  'baby arugula',
  'malted barley flour',
  'water',
  'mostaccioli',
  'coconut oil',
  'raspberry preserves',
  'colored nonpareils',
  'pineapple preserves',
  'sweet pickle relish',
  'buttermilk powder',
  'veggie dogs',
  'deli turkey',
  'whole garlic cloves',
  'chili garlic sauce',
  'pickled green beans',
  'fat free buttermilk',
  'salted pork fat',
  'tahini',
  'bouillon granules',
  'cooked bacon',
  'ground pork sausage',
  'unsalted pistachios',
  'gluten free granola',
  'marinated mushrooms',
  'roasted cashews',
  'mild cheddar cheese',
  'ground black pepper',
  'fine sea salt',
  'sesame oil',
  'cheerios',
  'dried apricots',
  'puffed rice cereal',
  'napa cabbage leaves',
  'caramel popcorn',
  'rice protein powder',
  'wheat thins',
  'gingersnap cookies',
  'benedictine',
  'rye flour',
  'hemp protein powder',
  'chocolate ice cream',
  'gluten free pasta',
  'cabernet sauvignon',
  'maraschino cherries',
  'off dry riesling',
  'sheep cheese',
  'filet mignon',
  'medium grain rice',
  'butter lettuce',
  'stilton',
  'escarole',
  'ground white pepper',
  'veggie bacon',
  'wheat chex cereal',
  'orecchiette',
  'candied orange peel',
  'corned beef brisket',
  'black mustard seeds',
  'kefir',
  'red snapper fillets',
  'zaatar',
  'imitation crab',
  'candied ginger',
  'elderflower liqueur',
  'quick cooking grits',
  'black nightshade',
  'crab boil seasoning',
  'beefsteak tomato',
  'bread machine yeast',
  'baking soda',
  'modeling chocolate',
  'coleslaw dressing',
  'decaf coffee',
  'potato starch',
  'whey protein powder',
  'beef patties',
  'banana pepper rings',
  'pastina',
  'angel food cake mix',
  'canned adzuki beans',
  'chocolate sprinkles',
  'coconut milk powder',
  'marshmallow bunnies',
  'canned coconut milk',
  'pumpkin pie mix',
  'honey dijon mustard',
  'cowpea green beans',
  'strawberry cake mix',
  'garden cress',
  'wild boar stew meat',
  'green pepper',
  'cooked pasta shells',
  'dried green lentils',
  'langostino tails',
  'brown mustard seeds',
  'whole grain mustard',
  'seedless red grapes',
  'granny smith apple',
  'chickpea flour',
  'cheddar cheese soup',
  'cooked rice noodles',
  'cooked jasmine rice',
  'golden oreos',
  'shortbread cookies',
  'passion fruit juice',
  'boneless pork roast',
  'sunflower seeds',
  'yukon gold potato',
  'ground bison',
  'canned tomato sauce',
  'dry roasted peanuts',
  'ener g egg replacer',
  'chicken breast meat',
  'tomatoes in juice',
  'japanese persimmon',
  'dried egg whites',
  'lucky charms cereal',
  'dijon mustard',
  'freekeh',
  'baby spinach',
  'cooked basmati rice',
  'pimenton de la vera',
  'conversation hearts',
  'cooked risotto rice',
  'watermelon radish',
  'dried brown lentils',
  'psyllium husks',
  'seedless watermelon',
  'whole wheat pasta',
  'beef shoulder roast',
  'nonfat sour cream',
  'cooked soba noodles',
  'punt e mes',
  'baby back ribs',
  'canned corona beans',
  'ground coffee',
  'chinese egg noodles',
  'spaghetti sauce mix',
  'sherry vinegar',
  'blue food color',
  'fingerling potato',
  'spinach tortellini',
  'protein powder',
  'tangerine',
  'porterhouse steak',
  'low fat cheese',
  'cooked red lentils',
  'chocolate frosting',
  'coconut meat',
  'chicken leg',
  'pea protein powder',
  'chartreuse',
  'gluten free bagel',
  'unbaked pie crust',
  'cooked sticky rice',
  'digestive biscuits',
  'froot loops cereal',
  'turmeric',
  'red food color',
  'bone in pork roast',
  'lemonade mix',
  'canned pigeon peas',
  'pumpernickel',
  'marshmallow cream',
  'country style ribs',
  'peppermint patties',
  'dried basil',
  'white wine vinegar',
  'miso',
  'cooked spaghettini',
  'pickle relish',
  'colored sprinkles',
  'cheesecake mix',
  'sirloin tip steak',
  'tomato concentrate',
  'wild boar shoulder',
  'cooked white rice',
  'pineapple in juice',
  'coarse kosher salt',
  'curly parsley',
  'vegetable broth',
  'lower sodium shoyu',
  'fresh green beans',
  'dried onion flakes',
  'chickpea spaghetti',
  'mini peppers',
  'apple',
  'red chili pepper',
  'safflower oil',
  'chocolate cake mix',
  'brewed coffee',
  'mixed greens',
  'butterflied trout',
  'canned lychees',
  'chestnut mushrooms',
  'jarrahdale squash',
  'self rising flour',
  'ancho chili powder',
  'tiger shrimp',
  'taco seasoning mix',
  'fresh thyme',
  'nutri grain cereal',
  'pink banana squash',
  'marzipan',
  'extra dry prosecco',
  'dried strawberries',
  'jumbo pasta shells',
  'yeast dinner rolls',
  'sweet yellow onion',
  'peppermint extract',
  'bean sprouts',
  'caramelized onions',
  'trimmed watercress',
  'lean rack of lamb',
  'canned white beans',
  'chicken drumettes',
  'puff pastry sheets',
  'fresh corn',
  'ovaltine',
  'vanilla paste',
  'canned pinto beans',
  'goldfish crackers',
  'sesame seeds',
  'butternut squash',
  'raisin bran',
  'sweet chili sauce',
  'bison tenderloin',
  'mini filo shells',
  'gochujang',
  'dried kidney beans',
  'coffee beans',
  'dried adzuki beans',
  'yellow spice drops',
  'corn flakes',
  'walla walla',
  'dried butter beans',
  'nacho cheese',
  'plain greek yogurt',
  'cooked tagliatelle',
  'tagatose',
  'curly leaf lettuce',
  'peanut butter cups',
  'prime rib',
  'desiccated coconut',
  'strawberry sauce',
  'spinach fettuccine',
  'tempura batter mix',
  'defatted soy flour',
  'jumbo marshmallows',
  'cress seed',
  'cocoa puffs cereal',
  'canned black beans',
  'vegan cream cheese',
  'cooked egg noodles',
  'gingerbread spice',
  'barbecue seasoning',
  'puff pastry shells',
  'cucumber',
  'cooked short pasta',
  'cherry pie filling',
  'liquor',
  'fresh corn kernels',
  'black sesame seeds',
  'bison short ribs',
  'belacan',
  'soy flour',
  'yellow curry paste',
  'red belgian endive',
  'caviar substitute',
  'sweet potato puree',
  'white shoepeg corn',
  'thick cut bacon',
  'golden brown sugar',
  'canned fava beans',
  'rump roast',
  'pepperjack cheese',
  'banana pudding mix',
  'andouille sausage',
  'garlic oil',
  'short grain rice',
  'yardlong beans',
  'strawberry yogurt',
  'white kidney beans',
  'chocolate shavings',
  'ground fennel',
  'cocktail sausages',
  'herbes de provence',
  'cooked grain blend',
  'cooked pappardelle',
  'kaffir lime leaves',
  'dried corona beans',
  'soy buttery spread',
  'cooked penne',
  'white fish fillets',
  'turkish bay leaves',
  'jumbo shrimp',
  'fresh basil',
  'bacon',
  'malted milk powder',
  'dry onion soup mix',
  'orange zest',
  'bran flakes',
  'soy protein powder',
  'swiss cheese',
  'bone in pork chops',
  'bison strip loin',
  'spaghetti squash',
  'butterscotch chips',
  'blood orange juice',
  'turkey wings',
  'hot cherry pepper',
  'gingersnap crumbs',
  'marshmallow chicks',
  'chipolata',
  'angel hair pasta',
  'pineapple tidbits',
  'rice vinegar',
  'berbere',
  'gorgonzola',
  'baby leaf lettuce',
  'horseradish root',
  'fresh mint',
  'sweet corn',
  'english cucumber',
  'capellini',
  'fiddleheads',
  'ground cumin',
  'masa harina',
  'taco salad shells',
  'grape nuts cereal',
  'dried mung beans',
  'spinach wrap',
  'chocolate cookies',
  'apricot preserves',
  'roasting chicken',
  'blood orange zest',
  'framboise liqueur',
  'cinnamon schnapps',
  'gluten free flour',
  'cavatelli',
  'cooked fettuccine',
  'raw pumpkin seeds',
  'kit kat',
  'mung bean sprouts',
  'dried fruit',
  'lemon zest',
  'fresh herbs',
  'dry seasoning rub',
  'physalis',
  'sourdough starter',
  'cooked buckwheat',
  'cheese tortellini',
  'ground round',
  'gluten free wrap',
  'cooked black rice',
  'cooked long pasta',
  'basil oil',
  'asafoetida',
  'amaretti cookies',
  'seedless cucumber',
  'vegan cheese',
  'bison back ribs',
  'sugar substitute',
  'artichoke bottoms',
  'green beans',
  'marshmallow peeps',
  'frozen cheesecake',
  'dried pigeon peas',
  'veggie nuggets',
  'chow mein noodles',
  'angostura bitters',
  'cooked cannelloni',
  'canned navy beans',
  'hungarian paprika',
  'pork belly slices',
  'cornish hens',
  'pointed pepper',
  'golden kiwi',
  'dried mango',
  'pumpkin pie spice',
  'canned beef broth',
  'egg roll wrappers',
  'gravlax',
  'turkey meatballs',
  'curry powder',
  'pomegranate syrup',
  'littleneck clams',
  'multigrain bread',
  'crushed ice cubes',
  'shortcrust pastry',
  'tuna in olive oil',
  'romaine hearts',
  'pork rinds',
  'all purpose flour',
  'cumin seeds',
  'funfetti cake mix',
  'double gloucester',
  'starburst candies',
  'soft cheese',
  'seafood seasoning',
  'chocolate extract',
  'green peppercorns',
  'lean filet mignon',
  'cooked tortellini',
  'whole wheat rolls',
  'dried pinto beans',
  'dried fava beans',
  'raspberry liqueur',
  'nondairy creamer',
  'light brown sugar',
  'almond bark',
  'beef stock powder',
  'cooked brown rice',
  'liquid egg whites',
  'lebanese cucumber',
  'cooked split peas',
  'raspberry vinegar',
  'emmantaler cheese',
  'watercress',
  'fat free yogurt',
  'dried white beans',
  'pasta dough',
  'gluten free bread',
  'soy nuts',
  'tart cherries',
  'wide egg noodles',
  'crushed pineapple',
  'mango puree',
  'dried red lentils',
  'mascarpone',
  'acai powder',
  'white grape juice',
  'breadstick dough',
  'cooked orzo',
  'red pepper',
  'baharat',
  'hollandaise sauce',
  'granulated garlic',
  'truffle mushrooms',
  'bluefish fillets',
  'fresh ginger',
  'aioli',
  'farfalle',
  'chocolate chips',
  'breakfast sausage',
  'whole wheat bread',
  'tricolor pasta',
  'canned jackfruit',
  'jalapeno pepper',
  'ground chuck',
  'watermelon',
  'almond oil',
  'mahi mahi fillets',
  'dried black beans',
  'old bay seasoning',
  'mixed baby greens',
  'potstickers',
  'herring fillets',
  'mixed fresh fruit',
  'canned lima beans',
  'chinese rice wine',
  'sunflower shoots',
  'vanilla ice cream',
  'lean chuck steak',
  'turkey drumsticks',
  'split pigeon peas',
  'chicken seasoning',
  'beef franks',
  'whole kernel corn',
  'lamb stock powder',
  'rubbed sage',
  'dried blueberries',
  'whitefish fillets',
  'delicata squash',
  'pinot grigio',
  'peppercorns',
  'steel cut oats',
  'heirloom tomato',
  'puff pastry dough',
  'dehydrated garlic',
  'pattypan squash',
  'everything bagel',
  'lobster mushrooms',
  'japanese eggplant',
  'green curry paste',
  'red currant jelly',
  'apple pie filling',
  'pomegranate juice',
  'cube steak',
  '2 percent milk',
  'decorating gel',
  'lancashire',
  'manzanilla olives',
  'raspberry extract',
  'hawaiian rock cod',
  'cooked mung beans',
  'spaghetti',
  'cooked sushi rice',
  'lemon pie filling',
  'whole grain wrap',
  'almond meal',
  'neufchatel',
  'fresh sage',
  'marrow bones',
  'pepperoni',
  'european seabass',
  'corn flour',
  'dried cranberries',
  'white peppercorns',
  'pappardelle',
  'mixed seafood',
  'ground flaxseed',
  'cake flour',
  'sparkling water',
  'canned soybeans',
  'creamed corn',
  'sukrin',
  'matcha',
  'licorice extract',
  'brown rice syrup',
  'jarlsberg cheese',
  'chorizo crumbles',
  'chili with beans',
  'sweet rice flour',
  'lean corned beef',
  'vanilla frosting',
  'wheat flatbreads',
  'grape seed flour',
  'absinthe',
  'canned pineapple',
  'iceberg lettuce',
  'guajillo pepper',
  'yellow cornmeal',
  'chuck steak',
  'broccoli sprouts',
  'vegan mozzarella',
  'piquillo pepper',
  'tangelo',
  'tarragon vinegar',
  'sugar in the raw',
  'soy yogurt',
  'swordfish steaks',
  'beef chuck roast',
  'brown rice flour',
  'bean curd sheets',
  'celery rib',
  'hazelnut liqueur',
  'oyster mushrooms',
  'cooked crabmeat',
  'red pearl onion',
  'sauvignon blanc',
  'vegan sour cream',
  'ground fenugreek',
  'pink lady apple',
  'cannellini beans',
  'greens',
  'canned mushrooms',
  'maple syrup',
  'macaroni',
  'rigatoni',
  'crushed tomatoes',
  'catfish fillets',
  'starchy potato',
  'candied cherries',
  'broccoli florets',
  'green tea bag',
  'mounds bar',
  'vodka',
  'flat iron steak',
  'clementine juice',
  'cooked farro',
  'pumpkin blossoms',
  'hazelnut meal',
  'creole seasoning',
  'active dry yeast',
  'cipollini onions',
  'green onions',
  'amaretto liqueur',
  'lean ground lamb',
  'bitters',
  'beef round roast',
  'pork steaks',
  'dried barberries',
  'rice chex',
  'flounder fillets',
  'chambord',
  'cereal',
  'granulated onion',
  'pretzel nuggets',
  'mustard',
  'breadcrumbs',
  'round tip steak',
  'cherry preserves',
  'pork tenderloin',
  'beef tenderloin',
  'cooked manicotti',
  'chicken bouillon',
  'new potato',
  'venison shoulder',
  'pork loin chops',
  'clarified butter',
  'blanched almonds',
  'stevia',
  'sugar cookie mix',
  'buckwheat flour',
  'hard boiled egg',
  'wild blueberries',
  'yellow wax beans',
  'dried bay leaves',
  'chorizo sausages',
  'cooked capellini',
  'slivered almonds',
  'red kuri squash',
  'pie dough rounds',
  'poppyseed roll',
  'peas and carrots',
  'limoncello',
  'dried lima beans',
  'roquefort cheese',
  'baby carrots',
  'white grapefruit',
  'hersheys kisses',
  'popcorn kernels',
  'buttercup squash',
  'flavored butter',
  'virgin olive oil',
  'canned asparagus',
  'chocolate flakes',
  'dried onion',
  'black forest ham',
  'soy creamer',
  'dandelion greens',
  'hibiscus',
  'pepperoni slices',
  'cubanelle pepper',
  'chickpea pasta',
  'vegan mayonnaise',
  'saltine crackers',
  'asparagus',
  'provolone',
  'muscadine grapes',
  'ground allspice',
  'toffee bar candy',
  'green plantain',
  'black bean sauce',
  'chocolate chunks',
  'strawberry jelly',
  'southern comfort',
  'hot sauce',
  'superfine sugar',
  'sandwich cookies',
  'onion dip',
  'pineapple rings',
  'balsamic vinegar',
  'italian tomato',
  'vegeta',
  'blackberry juice',
  'golden cherries',
  'israeli couscous',
  'framboise lambic',
  'long hot pepper',
  'cod fillets',
  'cookie crumbs',
  'dark brown sugar',
  'flavoring syrup',
  'cantaloupe balls',
  'chicken schmaltz',
  'corn chex',
  'orange marmalade',
  'flax oil',
  'yellow plantain',
  'squash blossoms',
  'chilean seabass',
  'cookie butter',
  'anellini pasta',
  'fish sauce',
  'zucchini noodles',
  'taco shells',
  'preserved lemon',
  'pointed cabbage',
  'flacourtia',
  'sugar free jelly',
  '20 percent quark',
  'boiling potato',
  'cashew fruit',
  'red wine vinegar',
  'wonton wrappers',
  'seasoning mix',
  'brussels sprouts',
  'seabass fillets',
  'vanilla cake mix',
  'mandarin oranges',
  'cream of coconut',
  'strawberry puree',
  'moringa leaves',
  'smoked ham hock',
  'mitsuba',
  'star anise',
  'cooked spaghetti',
  'blueberry bagel',
  'liquid sucralose',
  'persian cucumber',
  'mackerel',
  'camembert',
  'cooked wild rice',
  'light soy sauce',
  'bread dough',
  'red leaf lettuce',
  'pumpkin seed oil',
  'fresh bay leaves',
  'bucatini',
  'tamari',
  'enchilado cheese',
  'leg of wild boar',
  'unsalted peanuts',
  'monkfish fillets',
  'dried navy beans',
  'blackeyed peas',
  'dried green peas',
  'sourdough bread',
  '40 percent quark',
  'dried tortellini',
  'oil packed tuna',
  'kalamata olives',
  'apple jelly',
  'shucked oysters',
  'veal loin chops',
  'cajun seasoning',
  'canned tomatoes',
  'chickpea leaves',
  'salt cod',
  'aloe vera juice',
  'baking potato',
  'pecorino',
  'pork loin',
  'honeydew melon',
  'chocolate curls',
  'wild boar shank',
  'bengal gram',
  'lambsquarters',
  'ground cinnamon',
  'cooked ditalini',
  'monkfish cheeks',
  'safflower seeds',
  'canned mackerel',
  'hersheys cocoa',
  'pasta salad mix',
  'stinging nettle',
  'cavatappi',
  'french dressing',
  'cashew milk',
  'grapefruit zest',
  'custard powder',
  'vegetable juice',
  'kecap manis',
  'whiting fillets',
  'orange',
  'taleggio cheese',
  'seedless grapes',
  'light olive oil',
  'baby artichoke',
  'raw shrimp',
  'braeburn apple',
  'dried marjoram',
  'maple flavoring',
  'beef short ribs',
  'thai fish sauce',
  'tamarind juice',
  'pickling spices',
  'creamed coconut',
  'grenadine',
  'barnyard millet',
  'shredded cheese',
  'squid ink pasta',
  'hokkien noodles',
  'top blade steak',
  'dr pepper',
  'fresh dill',
  'grill seasoning',
  'white zinfandel',
  'halloumi',
  'pineapple juice',
  'biscuits',
  'crawfish tails',
  'cardamom powder',
  'saffron',
  'fenugreek seeds',
  'belgian endive',
  'salsa verde',
  'palm sugar',
  'greek seasoning',
  'steak seasoning',
  'cooked amaranth',
  'tamarind',
  'whipped topping',
  'yellow cake mix',
  'ground espresso',
  'corn husks',
  'banana blossoms',
  'baby corn',
  'coarse sea salt',
  'turkey sausage',
  'cornmeal',
  'alfalfa sprouts',
  'juniper berries',
  'fresine',
  'tortilla chips',
  'dried pineapple',
  'candied almonds',
  'orange juice',
  'grouper fillets',
  'grilling cheese',
  'yellow tomato',
  'pudding mix',
  'minute tapioca',
  'pizza seasoning',
  'white chocolate',
  'manchego cheese',
  'orange tomato',
  'english muffin',
  'bone broth',
  'roasted chicken',
  'raspberry jelly',
  'water chestnuts',
  'ice cream cone',
  'zucchini',
  'tortilla strips',
  'almond milk',
  'purple potato',
  'chicken cutlet',
  'oyster crackers',
  'all bran cereal',
  'fresh anchovies',
  'raspberry sauce',
  'cooked couscous',
  'lemon lime pop',
  'vegetable stock',
  'entrecote steak',
  'chicken giblets',
  'cream of tartar',
  'canned sardines',
  'ahi tuna steak',
  'dungeness crab',
  'frozen biscuits',
  'wild boar chops',
  'chicken tenders',
  'caramel candy',
  'morel mushrooms',
  'stick margarine',
  'pizza dough mix',
  'cooked linguine',
  'anchovy fillets',
  'grilled chicken',
  'ginger powder',
  'cranberry juice',
  'pasta sauce',
  'mcintosh apple',
  'bouillon powder',
  'cheshire cheese',
  'english mustard',
  'elk roast',
  'lamb loin chop',
  'tubettini',
  'sausage links',
  'poblano pepper',
  'tilapia fillets',
  'cheese ravioli',
  'walnuts',
  'root vegetable',
  'cranberry beans',
  'long grain rice',
  'corn on the cob',
  'coconut vinegar',
  'lo mein noodles',
  'russet potato',
  'red curry paste',
  'blueberry jelly',
  'stewed tomatoes',
  'peach preserves',
  'rosemary',
  'parmesan',
  'orange slices',
  'lingonberry jam',
  'rice vermicelli',
  'bok choy leaves',
  'chestnut flour',
  'licorice twists',
  'dried soybeans',
  'anaheim pepper',
  'yellowfin tuna',
  'pumpkin seeds',
  'enchilada sauce',
  'milk substitute',
  'cooked rigatoni',
  'broccoli',
  'vanilla yogurt',
  'turkey gizzards',
  'snapper fillets',
  'baguette',
  'chicken breast',
  'turkey pastrami',
  'dried dill',
  'instant oatmeal',
  'tangerine juice',
  'farmer cheese',
  'water spinach',
  'dark sesame oil',
  'adobo seasoning',
  'agnolotti',
  'candied walnuts',
  'walnut pieces',
  'tarragon',
  'velveeta cheese',
  'unsalted butter',
  'baby lima beans',
  'fresh mushrooms',
  'pork spare ribs',
  'matzo',
  'habanero chili',
  'dark corn syrup',
  'fuyu persimmon',
  'nabulsi',
  'brownie mix',
  'anisette',
  'tamarind leaves',
  'enoki mushrooms',
  'food color',
  'lamb stew meat',
  'mezzelune',
  'apple pie spice',
  'corkscrew pasta',
  'chocolate glaze',
  'cinnamon stick',
  'muenster',
  'corn muffin mix',
  'halibut fillets',
  'canned zucchini',
  'sheet gelatin',
  'persimmon',
  'turkey kielbasa',
  'vienna sausage',
  'haddock fillets',
  'baby zucchini',
  'extra firm tofu',
  'cooked chicken',
  'turbinado sugar',
  'blueberry juice',
  'chocolate syrup',
  'beef strip loin',
  'white cornmeal',
  'roasted peanuts',
  'ground elk',
  'banana shallot',
  'wasabi paste',
  'spanish chorizo',
  'muscovado sugar',
  'bacon drippings',
  'sugar snap peas',
  'golden berries',
  'spice cake mix',
  'sola sweetener',
  'chili pepper',
  'fruit cocktail',
  'glutinous rice',
  'mashed papaya',
  'fresh lavender',
  'candied citron',
  'muesli',
  'salami',
  'couscous',
  'chex mix',
  'avocado halves',
  'roasted garlic',
  'red grapefruit',
  'venison steak',
  'oregano',
  'turkey berries',
  'moringa powder',
  'green tomato',
  'lemon cake mix',
  'coconut aminos',
  'whole milk',
  'black licorice',
  'pork seasoning',
  'ground chicken',
  'dessert shells',
  'paprika',
  'olive tapenade',
  'sparkling wine',
  'pumpkin leaves',
  'dark chocolate',
  'amaranth',
  'diet coke',
  'apricot nectar',
  'baby eggplant',
  'cardamom pods',
  'soy butter',
  'quinoa pasta',
  'sugar free jam',
  'farfalle tonde',
  'ditalini',
  'black cherries',
  'radish sprouts',
  'mexican crema',
  'concord grapes',
  'salmon fillets',
  '1 percent milk',
  'coconut butter',
  'tri tip steak',
  'lobster',
  'cornbread mix',
  'pigeon breasts',
  'kielbasa',
  'kimchi',
  'havarti',
  'seasoned salt',
  'smoked paprika',
  'turkey giblets',
  'mustard greens',
  'gruyere',
  'red cabbage',
  'black currants',
  'cinnamon sugar',
  'munster',
  'pistachio nuts',
  'fresh marjoram',
  'corn tortilla',
  'candied fruit',
  'dried currants',
  'turkey breast',
  'fine cornmeal',
  'sandwich bun',
  'semolina flour',
  'spinach',
  'globe eggplant',
  'marinara sauce',
  'tzatziki',
  'dry yeast',
  'pork escalopes',
  'hazelnut flour',
  'lavender syrup',
  'empanada dough',
  'lavender honey',
  'smoked haddock',
  'arugula',
  'orange bitters',
  'french mustard',
  'palm oil',
  'tortilla',
  'crocodile meat',
  'white cake mix',
  'fresno pepper',
  'lamb rib chops',
  'daikon sprouts',
  'pearl barley',
  'gigante beans',
  'shirataki rice',
  'cayenne pepper',
  'flavored sugar',
  'endive',
  'scotch whiskey',
  'golden raisins',
  'chicken thighs',
  'cooked lentils',
  'pasilla pepper',
  'shiso leaves',
  'hubbard squash',
  'diet root beer',
  'collard greens',
  'chicken hearts',
  'bourbon',
  'guinness',
  'dried tarragon',
  'pecan pieces',
  'lettuce leaf',
  'bramley apple',
  'sandwich thin',
  'banana extract',
  'chayote',
  'canned lentils',
  'elk tenderloin',
  'edible flowers',
  'peach schnapps',
  'sweet potato',
  'turkey gravy',
  'whipping cream',
  'nori',
  'ground clove',
  'brewers yeast',
  'hearts of palm',
  'fresh sardines',
  'plum preserves',
  'italian bread',
  'halibut steaks',
  'coffee extract',
  'squid tubes',
  'pork and beans',
  'red tea bag',
  'chipotle paste',
  'dry white wine',
  'parsley',
  'frozen spinach',
  'marie biscuits',
  'rotini',
  'balsamic glaze',
  'bartlett pear',
  'bottled garlic',
  'vidalia onion',
  'banana pepper',
  'milk chocolate',
  'cream of wheat',
  'fontina cheese',
  'falernum syrup',
  'low carb bread',
  'chickpea penne',
  'beef stew meat',
  'frozen waffles',
  'tostada shell',
  'sirloin steak',
  'granola',
  'french lentils',
  'chickpeas',
  'black tea bag',
  'kamut',
  'demerara sugar',
  'sweet gherkins',
  'reeses pieces',
  'turmeric paste',
  'sliced almonds',
  'seasoned flour',
  'pretzel twists',
  'canned herring',
  'blackberry jam',
  'jalapeno jelly',
  'cheddar cheese',
  'annatto',
  'borlotti beans',
  'candied pecans',
  'fish seasoning',
  'lump crabmeat',
  'bratwurst bun',
  'gnocchi',
  'roselle fruit',
  'mashed banana',
  'chokeberries',
  'onion powder',
  'bread bowls',
  'mustard powder',
  'coconut flakes',
  'brut cava',
  'ketchup',
  'macadamia nuts',
  'ipa',
  'hawaiian bread',
  'elbow macaroni',
  'hazelnut milk',
  'mangold',
  'orange liqueur',
  'white potato',
  'avocado slices',
  'avocado leaves',
  'pickled daikon',
  'grape seed oil',
  'spices',
  'cooked pasta',
  'pork rib roast',
  'cannoli shells',
  'stuffing',
  'tapioca',
  'whole chicken',
  'canned chicken',
  'browning sauce',
  'creme de cacao',
  'ground savory',
  'bottled ginger',
  'beef soup bone',
  'ciabatta roll',
  'pretzel sticks',
  'finger chili',
  'seitan cutlets',
  'ground sirloin',
  'nopales',
  'cinnamon roll',
  'blue spirulina',
  'cooked bulgur',
  'sweet cherries',
  'plaice',
  'grape tomato',
  'mexican cheese',
  'ciabatta',
  'pangasius',
  'hass avocado',
  'cheese pumpkin',
  'mache',
  'pickled ginger',
  'chicken liver',
  'whole tomato',
  'bouillon cube',
  'cooked gemelli',
  'lemon juice',
  'burrata',
  'cushaw squash',
  'ground venison',
  'vanilla powder',
  'salad dressing',
  'creole mustard',
  'banana liqueur',
  'quorn crumbles',
  'mixed fruit',
  'kabocha squash',
  'cracker crumbs',
  'red onion',
  'paratha',
  'celery leaves',
  'potato leaves',
  'black walnuts',
  'challah',
  'lacinato kale',
  'lime juice',
  'tubetti',
  'lamb shoulder',
  'dried lentils',
  'navel orange',
  'oaxaca cheese',
  'blood orange',
  'mango extract',
  'bouquet garni',
  'bitter gourd',
  'mixed berries',
  'bamboo shoots',
  'shell topping',
  'hot dog bun',
  'black treacle',
  'maple extract',
  'jamon serrano',
  'turnip greens',
  'green cabbage',
  'roma tomato',
  'raisins',
  'edamame',
  'pico de gallo',
  'venison chops',
  'huckleberries',
  'gammon steak',
  'barley flakes',
  'pork knuckle',
  'coconut cream',
  'pointed gourd',
  'frozen yogurt',
  'salted butter',
  'rabbit meat',
  'pasta ribbons',
  't bone steak',
  'cluster bean',
  'coconut wrap',
  'coleslaw mix',
  'sea vegetable',
  'beef ravioli',
  'seitan steaks',
  'peanut oil',
  'langsat',
  'cashew butter',
  'green papaya',
  'almond butter',
  'sugar alcohol',
  'diced venison',
  'peanut butter',
  'fusilli',
  'amchar masala',
  'daikon radish',
  'passion fruit',
  'galangal',
  'ribs',
  'chicken gravy',
  'mango chutney',
  'green mango',
  'dried coconut',
  'salmon caviar',
  'orange roughy',
  'liquid stevia',
  'brown lentils',
  'romano cheese',
  'charoli seeds',
  'summer savory',
  'liquid pectin',
  'bison steak',
  'diet pop',
  'dark molasses',
  'vanilla bean',
  'cracked wheat',
  'custard apple',
  'garlic powder',
  'bonito flakes',
  'canned salmon',
  'mini m&ms',
  'chicken broth',
  'picante sauce',
  'anise extract',
  'tamarillo',
  'caper berries',
  'perch',
  'boysenberries',
  'radish leaves',
  'turkey thigh',
  'soymilk',
  'aleppo pepper',
  'finger millet',
  'suze',
  'rack of lamb',
  'chicken bones',
  'honey mustard',
  'broccoli rabe',
  'garlic scapes',
  'yellow onion',
  'arborrio rice',
  'cassava flour',
  'chai tea bag',
  'wheatberries',
  'wasabi powder',
  'hemp oil',
  'toffee',
  'bilimbi fruit',
  'turkey hearts',
  'meatloaf mix',
  'dragon fruit',
  'sorghum flour',
  'blackberries',
  'tapioca syrup',
  'mixed spice',
  'rice bran oil',
  'baby bok choy',
  'whole coconut',
  'tabasco sauce',
  'writing icing',
  'nutmeg',
  'cashew halves',
  'espresso',
  'mineral water',
  'black vinegar',
  'brut prosecco',
  'earl grey',
  'creme fraiche',
  'zinfandel',
  'celery flakes',
  'paneer',
  'pickled beets',
  'toffee pieces',
  'pawpaw',
  'rainbow trout',
  'fat free milk',
  'raspberry jam',
  'dried epazote',
  'chicken stock',
  'avocado cubes',
  'fregula',
  'mustard seeds',
  'pineapple jam',
  'broccoli slaw',
  'sugar pumpkin',
  'kraft singles',
  'instant yeast',
  'royal porgy',
  'soft pretzels',
  'caraway seeds',
  'margarita mix',
  'liverwurst',
  'lemon essence',
  'powdered milk',
  'fresh herring',
  'beef bouillon',
  'cooked rotini',
  'asiago cheese',
  'tangelo juice',
  'walnut halves',
  'grand marnier',
  'smoked salmon',
  'annatto seeds',
  'lemon extract',
  'blueberry jam',
  'gelling sugar',
  'golden syrup',
  'tomato slices',
  'spam',
  'challah roll',
  'winter squash',
  'plain doritos',
  'coconut flour',
  'coconut water',
  'fat of choice',
  'sunflower oil',
  'pistachio oil',
  'fresh epazote',
  'sweet pickles',
  'banana leaves',
  'vanilla sugar',
  'thin baguette',
  'seafood stock',
  'bulgur',
  'runner beans',
  'pomfret',
  'anjou pear',
  'tamarind pulp',
  'garam masala',
  'anchovy paste',
  'goat cheese',
  'jamon iberico',
  'savoy cabbage',
  'long pepper',
  'penne',
  'spring onions',
  'instant grits',
  'cooking spray',
  'lucuma powder',
  'cotija cheese',
  'sweet paprika',
  'refried beans',
  'dried peaches',
  'cornmeal mix',
  'tri tip roast',
  'palmyra',
  'fennel pollen',
  'canned sprats',
  'whipped cream',
  'baking powder',
  'summer squash',
  'pork sausage',
  'waxy potato',
  'salmon steak',
  'clotted cream',
  'trout fillets',
  'lobster tails',
  'alcohol',
  'lingonberries',
  'potato chips',
  'single cream',
  'beef consomme',
  'almonds',
  'medjool dates',
  'glucose syrup',
  'bison roast',
  'fig jam',
  'plum tomato',
  'quinoa flakes',
  'shaoxing wine',
  'hake',
  'poached egg',
  'kirsch',
  'green olives',
  'kahlua',
  'hot dogs',
  'curry leaves',
  'golden beet',
  'udon noodles',
  'ginger juice',
  'pigeon',
  'pine nuts',
  'shrimp stock',
  'pearl onion',
  'kidney beans',
  'black olives',
  'tomato puree',
  'black grapes',
  'turkey liver',
  'dry red wine',
  'curly endive',
  'venison loin',
  'oatmeal',
  'fatback',
  'pork cutlets',
  'pasta shells',
  'marshmallows',
  'beef kidney',
  'bottle gourd',
  'meyer lemon',
  'peach nectar',
  'tomato pesto',
  'sweet pepper',
  'canned beans',
  'duck breast',
  'sumac',
  'grape leaves',
  'hoisin sauce',
  'pork kidney',
  'strawberries',
  'nilla wafers',
  'green prawns',
  'plum vinegar',
  'thyme',
  'oyster sauce',
  'spanish rice',
  'pastry dough',
  'pretzel rods',
  'grain blend',
  'corona beans',
  'betel leaves',
  'graham flour',
  'brioche bun',
  'colby cheese',
  'frozen pizza',
  'potato salad',
  'dry riesling',
  'mango nectar',
  'gouda',
  'sea cucumber',
  'cocoa powder',
  'corn kernels',
  'coarse sugar',
  'green apple',
  'lavash bread',
  'peanut flour',
  'pastry flour',
  'bay scallops',
  'manila clams',
  'pear liqueur',
  'cherry juice',
  'whole clove',
  'slider buns',
  'ajwain',
  'fennel bulb',
  'cream sherry',
  'amaro',
  'dry vermouth',
  'fleur de sel',
  'ginger paste',
  'bagel chips',
  'goji berries',
  'sweet onion',
  'fried onions',
  'white onion',
  'pimms',
  'turkey necks',
  'carob powder',
  'langoustines',
  'lillet blanc',
  'puffed rice',
  'crusty roll',
  'millet flour',
  'mango sorbet',
  'barley flour',
  'chablis',
  'orgeat syrup',
  'fruit slices',
  'kelp noodles',
  'mint chutney',
  'ziti',
  'madeira',
  'turkey broth',
  'liquid smoke',
  'quinoa flour',
  'cheese curds',
  'liquid honey',
  'almond flour',
  'lobster meat',
  'quark',
  'almond paste',
  'rice noodles',
  'chicken feet',
  'agave',
  'toast',
  'chili beans',
  'round steak',
  'winged bean',
  'peach sorbet',
  'smoked trout',
  'amchoor',
  'carrot juice',
  'sugar apple',
  'guava nectar',
  'dried apples',
  'chicken base',
  'dried shrimp',
  'purple plum',
  'gooseberries',
  'dry couscous',
  'au jus',
  'burdock root',
  'bell pepper',
  'butterscotch',
  'adzuki beans',
  'fish fillets',
  'lemon sorbet',
  'chaat masala',
  'red currants',
  'crusty bread',
  'napa cabbage',
  'cooked rice',
  'tomato juice',
  'simple syrup',
  'pomegranate',
  'muscovy duck',
  'stock powder',
  'marsala',
  'white pepper',
  'tomato paste',
  'wondra flour',
  'veal cutlet',
  'whole turkey',
  'niger seed',
  'canned beets',
  'durian',
  'tartar sauce',
  'striped bass',
  'pesto',
  'ginseng root',
  'flank steak',
  'comte',
  'ground thyme',
  'turkey bacon',
  'pearl millet',
  'hazelnut oil',
  'fresh chives',
  'fresh nutmeg',
  'celery seed',
  'lemon wedge',
  'wheat flakes',
  'pork roast',
  'cooked grits',
  'dessert wine',
  'soybean oil',
  'stuffing mix',
  'tater tots',
  'canola oil',
  'whole rabbit',
  'red snapper',
  'tomato sauce',
  'dried chives',
  'turkey stock',
  'sapote',
  'dill pickles',
  'seitan',
  'baking mix',
  'garlic paste',
  'elk sausage',
  'cookies',
  'cream cheese',
  'basmati rice',
  'butter beans',
  'soba noodles',
  'potato bread',
  'potato roll',
  'sour cream',
  'beef brisket',
  'blueberries',
  'french bread',
  'banana bread',
  'malt vinegar',
  'black pepper',
  'candied nuts',
  'wine vinegar',
  'guava shells',
  'falsa',
  'scallops',
  'acorn squash',
  'longan',
  'pastry cream',
  'bison',
  'green grapes',
  'cacao powder',
  'aji amarillo',
  'greek olives',
  'liver cheese',
  'matzo meal',
  'jasmine rice',
  'venison ribs',
  'black quinoa',
  'lamb cutlets',
  'cooked spelt',
  'double cream',
  'elderberries',
  'banana chips',
  'fennel seeds',
  'texas toast',
  'ridge gourd',
  'pear nectar',
  'rum extract',
  'mini bagel',
  'beef shank',
  'raspberries',
  'pork shank',
  'file powder',
  'pita',
  'runny honey',
  'banana',
  'guinea fowl',
  'lamb shanks',
  'fruit juice',
  'garlic salt',
  'beef liver',
  'clear honey',
  'black plum',
  'coarse salt',
  'lollo rosso',
  'raw cashews',
  'canned tuna',
  'sword beans',
  'celeriac',
  'xanthan gum',
  'mint',
  'truffle oil',
  'anise',
  'ground sage',
  'andes mints',
  'maca',
  'shiraz',
  'adobo sauce',
  'ghee',
  'blue cheese',
  'brie',
  'guava juice',
  'maple sugar',
  'cantaloupe',
  'ripe olives',
  'gala apple',
  'feta cheese',
  'edam cheese',
  'clear glaze',
  'spaghettini',
  'turkey leg',
  'dried thyme',
  'tagliatelle',
  'spice paste',
  'brazil nuts',
  'onion roll',
  'soured milk',
  'neem leaves',
  'rye berries',
  'red lentils',
  'celery salt',
  'egg whites',
  'ginger',
  'lemon sugar',
  'biscuit mix',
  'chili paste',
  'tonic water',
  'citric acid',
  'beef hearts',
  'dried herbs',
  'fresh pasta',
  'kelp flakes',
  'fresh yeast',
  'cooking oil',
  'grapefruit',
  'ground pork',
  'yacon syrup',
  'canned peas',
  'pancake mix',
  'ponzu sauce',
  'rooibos',
  'skate wings',
  'lotus root',
  'cedar plank',
  'eggbeaters',
  'pigeon peas',
  'avocado oil',
  'starch',
  'neem fruit',
  'veal shank',
  'curry paste',
  'pinto beans',
  'lychee',
  'tart apple',
  'yeast water',
  'brown sugar',
  'cauliflower',
  'buttermilk',
  'tart shells',
  'horseradish',
  'canned fish',
  'leg of lamb',
  'whole goose',
  'wensleydale',
  'hemp seeds',
  'lemon basil',
  'tonka beans',
  'katsu sauce',
  'spelt flour',
  'grape jelly',
  'apricot jam',
  'sugar cubes',
  'jobs tears',
  'veal liver',
  'cooked ziti',
  'wasabi peas',
  'bread cubes',
  'snake gourd',
  'orange peel',
  'silken tofu',
  'apple cider',
  'ground lamb',
  'corn starch',
  'mung beans',
  'dried pears',
  'nut butter',
  'turkey meat',
  'lime leaves',
  'white beans',
  'rose apple',
  'crispbread',
  'spiny gourd',
  'prunes',
  'tengra',
  'canned corn',
  'short pasta',
  'boston butt',
  'candy cane',
  'soppressata',
  'carob chips',
  'skirt steak',
  'sherry',
  'wheat flour',
  'dried beans',
  'khesari dal',
  'chili sauce',
  'country ham',
  'ginger ale',
  'baby shrimp',
  'ribbon fish',
  'corned beef',
  'kosher salt',
  'beet greens',
  'pizza sauce',
  'ginger beer',
  'steak sauce',
  'lime wedge',
  'edible gold',
  'tomato soup',
  'white bread',
  'chex cereal',
  'ground veal',
  'grape juice',
  'sticky rice',
  'popcorn',
  'petite peas',
  'baked beans',
  'whiskey',
  'duck liver',
  'spice drops',
  'brown gravy',
  'elderflower',
  'moscato',
  'alum',
  'cooked pork',
  'corn cereal',
  'bombay duck',
  'lemon thyme',
  'clementine',
  'irish cream',
  'swiss chard',
  'coconut rum',
  'goose liver',
  'frozen corn',
  'mustard oil',
  'kiwi',
  'green pesto',
  'whole duck',
  'basil pesto',
  'sponge cake',
  'taro leaves',
  'cranberries',
  'light cream',
  'lime slice',
  'lemon grass',
  'fava beans',
  'poppy seeds',
  'pork liver',
  'goat milk',
  'wax chilies',
  'egg noodles',
  'soy pudding',
  'rock shrimp',
  'red mullet',
  'apple juice',
  'pearl sugar',
  'cashews',
  'sprouts',
  'jelly beans',
  'ground mace',
  'fresh fruit',
  'sago',
  'sage',
  'dried sage',
  'flatbread',
  'salt',
  'irish moss',
  'caerphilly',
  'croissant',
  'white wine',
  'bael fruit',
  'tortellini',
  'white corn',
  'candy corn',
  'buckwheat',
  'pea shoots',
  'acai juice',
  'lamb liver',
  'rice flour',
  'cornbread',
  'egg yolk',
  'pepsi',
  'pork belly',
  'sushi rice',
  'pear juice',
  'mayonnaise',
  'pecans',
  'smoked ham',
  'pinot noir',
  'fuji apple',
  'erythritol',
  'chardonnay',
  'milk',
  'moth bean',
  'elk steak',
  'beef bone',
  'light beer',
  'pound cake',
  'flaxseed',
  'vegetable',
  'veal stock',
  'peanuts',
  'yuzu',
  'black rice',
  'muskmelon',
  'whitebait',
  'table salt',
  'egg',
  'white rice',
  'pork stock',
  'roast beef',
  'dry sherry',
  'ham hock',
  'onion salt',
  'quail eggs',
  'nonpareils',
  'tea bag',
  'black bass',
  'artichoke',
  'plum sauce',
  'spare ribs',
  'hummus',
  'lemon sole',
  'red grapes',
  'mint jelly',
  'lamb stock',
  'turkey fat',
  'lamb bones',
  'demi glace',
  'cuttlefish',
  'fresh peas',
  'triple sec',
  'light rum',
  'cherry jam',
  'corn chips',
  'cheese dip',
  'jackfruit',
  'pineapple',
  'wheat germ',
  'ham steak',
  'navy beans',
  'areca nut',
  'green peas',
  'soy sauce',
  'snow peas',
  'gem squash',
  'dried figs',
  'cassava',
  'cookie mix',
  'orzo',
  'beef jerky',
  'fresh figs',
  'veal chops',
  'boiled ham',
  'starfruit',
  'lamb chop',
  'gherkins',
  'couverture',
  'light tuna',
  'panela',
  'pork broth',
  'bay leaves',
  'sobrasada',
  'pita chips',
  'limonia',
  'mango pulp',
  'maui onion',
  'bacon bits',
  'breadfruit',
  'beet',
  'baby leeks',
  'veal bone',
  'beef gravy',
  'walnut oil',
  'pork bone',
  'beef cubes',
  'tomatillos',
  'sauerkraut',
  'fish',
  'rose water',
  'shark',
  'mulberries',
  'lemon peel',
  'chia seeds',
  'wheat beer',
  'eggplant',
  'long pasta',
  'fettuccine',
  'beef broth',
  'boquerones',
  'mangosteen',
  'steak',
  'beef stock',
  'broccolini',
  'lima beans',
  'spring mix',
  'knackwurst',
  'cocoa nibs',
  'corn syrup',
  'cream soda',
  'naan',
  'rice cakes',
  'dill seed',
  'icing',
  'swordfish',
  'soy cheese',
  'star apple',
  'shortening',
  'grits',
  'candlenuts',
  'lemon balm',
  'weisswurst',
  'prosciutto',
  'cooked ham',
  'lotus seed',
  'nectarine',
  'fish stock',
  'rice milk',
  'frangelico',
  'chai spice',
  'thai basil',
  'clam juice',
  'mortadella',
  'fresh tuna',
  'tiger nuts',
  'red apple',
  'lemon curd',
  'pork chops',
  'bosc pear',
  'meatballs',
  'yuzu juice',
  'black drum',
  'slab bacon',
  'amla',
  'bee pollen',
  'salmon roe',
  'brown rice',
  'baby beets',
  'dried mint',
  'oat flakes',
  'spiced rum',
  'stout',
  'tia maria',
  'lamb loin',
  'crabmeat',
  'ash gourd',
  'hare',
  'pot roast',
  'focaccia',
  'chili oil',
  'coriander',
  'diet cola',
  'lime zest',
  'salt pork',
  'wild fish',
  'root beer',
  'mincemeat',
  'agar',
  'rye bread',
  'dark beer',
  'red glaze',
  'pimiento',
  'pork ribs',
  'chia egg',
  'partridge',
  'osso buco',
  'olive oil',
  'dry cider',
  'raw sugar',
  'wild rice',
  'black tea',
  'tofu',
  'sea bream',
  'flounder',
  'cilantro',
  'coca cola',
  'mushrooms',
  'raw honey',
  'taro root',
  'suet',
  'ice cubes',
  'chocolate',
  'bluefish',
  'hemp milk',
  'saucisses',
  'oat milk',
  'lime curd',
  'plantain',
  'dill',
  'avocado',
  'salad oil',
  'sprinkles',
  'red pesto',
  'corn',
  'manicotti',
  'anchovies',
  'marmalade',
  'guanciale',
  'flax egg',
  'heath bar',
  'duck eggs',
  'soybeans',
  'red plum',
  'cointreau',
  'crawfish',
  'beef base',
  'preserves',
  'rock salt',
  'triticale',
  'grape jam',
  'lemon oil',
  'foie gras',
  'goose fat',
  'duck leg',
  'red beet',
  'chestnuts',
  'ez sweetz',
  'ice cream',
  'rice wine',
  'lime peel',
  'gum drops',
  'diced ham',
  'boar',
  'sablefish',
  'spirulina',
  'capicola',
  'rockfish',
  'carp',
  'whitefish',
  'port wine',
  'cava',
  'guacamole',
  'fine salt',
  'rosehips',
  'rice bran',
  'radicchio',
  'frog legs',
  'mahi mahi',
  'champagne',
  'wax beans',
  'hazelnuts',
  'allspice',
  'firm tofu',
  'sucralose',
  'wild leek',
  'rutabaga',
  'green tea',
  'passata',
  'cake mix',
  'marjoram',
  'verjus',
  'cod',
  'chicken',
  'oxtail',
  'kumquat',
  'currants',
  'cabbage',
  'rib tips',
  'ham bone',
  'jujubes',
  'iced tea',
  'allulose',
  'radish',
  'frosting',
  'pumpkin',
  'sea salt',
  'monkfish',
  'gomashio',
  'schmaltz',
  'lemonade',
  'bok choy',
  'twix',
  'elk',
  'sherbet',
  'potato',
  'mirepoix',
  'okara',
  'dark rum',
  'caviar',
  'gelatin',
  'guar gum',
  'vermouth',
  'jicama',
  'samphire',
  'linguine',
  'culantro',
  'scrapple',
  'pretzels',
  'tomato',
  'semolina',
  'oat bran',
  'cardamom',
  'pomelo',
  'choy sum',
  'grouper',
  'prosecco',
  'croutons',
  'escargot',
  'ravioli',
  'crackers',
  'reindeer',
  'snapper',
  'craisins',
  'red wine',
  'poussin',
  'crostini',
  'pheasant',
  'molasses',
  'chai',
  'rye beer',
  'rambutan',
  'rye meal',
  'hp sauce',
  'cinnamon',
  'pancetta',
  'calvados',
  'mexicorn',
  'seabass',
  'galliano',
  'ahi tuna',
  'squid',
  'biscotti',
  'sardines',
  'shallot',
  'cherries',
  'riesling',
  'parsnip',
  'catfish',
  'kohlrabi',
  'herring',
  'licor 43',
  'tostadas',
  'pork fat',
  'corn oil',
  'bottarga',
  'apricot',
  'redfish',
  'duck fat',
  'bouillon',
  'drambuie',
  'pastrami',
  'sausage',
  'vinegar',
  'ramson',
  'pils',
  'lentils',
  'oysters',
  'legumes',
  'halibut',
  'genever',
  'campari',
  'biltong',
  'mango',
  'chervil',
  'gemelli',
  'sucanat',
  'quince',
  'bologna',
  'seaweed',
  'splenda',
  'peppers',
  'sambuca',
  'chorizo',
  'sugar',
  'loquat',
  'cockles',
  'custard',
  'shrimp',
  'salsa',
  'venison',
  'whiting',
  'peach',
  'mussels',
  'turnip',
  'sorghum',
  'rhubarb',
  'polenta',
  'porgy',
  'xylitol',
  'epazote',
  'kidney',
  'caramel',
  'cachaca',
  'berries',
  'mct oil',
  'vanilla',
  'limeade',
  'coconut',
  'papaya',
  'tilapia',
  'brioche',
  'carrot',
  'pasta',
  'curacao',
  'octopus',
  'eggnog',
  'tequila',
  'mesclun',
  'chianti',
  'harissa',
  'yogurt',
  'lettuce',
  'jaggery',
  'feijoa',
  'haddock',
  'pickles',
  'tempeh',
  'nougat',
  'hominy',
  'sorrel',
  'pepper',
  'bagel',
  'celery',
  'pluot',
  'broth',
  'barley',
  'sorbet',
  'millet',
  'quinoa',
  'wakame',
  'pectin',
  'brandy',
  'wasabi',
  'merlot',
  'mezcal',
  'cumin',
  'cheese',
  'aperol',
  'butter',
  'fennel',
  'pernod',
  'tinda',
  'porter',
  'grouse',
  'capers',
  'sprats',
  'onion',
  'citron',
  'coffee',
  'garlic',
  'fruit',
  'squash',
  'gammon',
  'crepes',
  'olives',
  'mizuna',
  'chives',
  'turbot',
  'guava',
  'crisco',
  'clove',
  'grapes',
  'cognac',
  'salmon',
  'grappa',
  'tuna',
  'jelly',
  'ackee',
  'dates',
  'shoyu',
  'dulse',
  'dashi',
  'speck',
  'seeds',
  'yeast',
  'juice',
  'spelt',
  'gravy',
  'farro',
  'katuk',
  'liver',
  'herbs',
  'kombu',
  'skate',
  'brine',
  'clams',
  'plum',
  'raita',
  'honey',
  'quail',
  'lime',
  'mirin',
  'wrap',
  'ramps',
  'pear',
  'stock',
  'basil',
  'fudge',
  'cream',
  'okra',
  'lager',
  'khoa',
  'duck',
  'pisco',
  'bread',
  'jamon',
  'goose',
  'boule',
  'leek',
  'sake',
  'pike',
  'teff',
  'bran',
  'nuts',
  'eel',
  'rice',
  'veal',
  'kelp',
  'oats',
  'wine',
  'peas',
  'lamb',
  'yam',
  'meat',
  'beer',
  'beef',
  'sole',
  'figs',
  'pork',
  'crab',
  'ouzo',
  'kale',
  'tea',
  'gin',
  'ham',
  'ice',
  'ale',
  'jam',
  'rum',
] as const;

export const UNITS = [
  'Gherkin',
  'Italian tomato',
  'NLEA Serving',
  'NLEA serving',
  'Potato large',
  'Potato medium',
  'Potato small',
  'Tbsp',
  'Triscuit Bit',
  'almond',
  'anchovie',
  'anchovy',
  'anisette sponge',
  'apricot',
  'artichoke',
  'avocado',
  'baby ear',
  'back with skin',
  'bag',
  'baguette',
  'ball',
  'balsam pear',
  'bar',
  'bar bite size',
  'bar fun size',
  'bar king size',
  'bar snack size',
  'batch',
  'bean',
  'beet',
  'berrie',
  'bird',
  'biscuit',
  'biscuit oblong',
  'biscuits round',
  'bite size',
  'block',
  'bolt',
  'bottle',
  'bottle NFS',
  'box',
  'breakfast treat',
  'breast',
  'brisket',
  'bulb',
  'bun',
  'bunch',
  'bundle',
  'bunnie',
  'bunny',
  'cake',
  'can',
  'can drained',
  'can or bottle',
  'can yield',
  'cap',
  'carton',
  'chayote',
  'cherrie',
  'cherry',
  'chick',
  'chicken',
  'chip',
  'chop',
  'clove',
  'cob',
  'coconut yield',
  'cone',
  'container',
  'cookie',
  'crab',
  'cracker',
  'cracker square',
  'crackers square',
  'crispbread',
  'croissant',
  'crown',
  'crust',
  'cube',
  'cubic inch',
  'cucumber',
  'cup',
  'cup BB',
  'cup aril',
  'cup chip',
  'cup chopped',
  'cup crumbled',
  'cup cut',
  'cup diced',
  'cup drained',
  'cup dry',
  'cup grated',
  'cup gumdrop',
  'cup kernel',
  'cup leave',
  'cup mashed',
  'cup packed',
  'cup piece',
  'cup section',
  'cup shelled',
  'cup shredded',
  'cup sifted',
  'cup slice',
  'cup sliced',
  'cup sprig',
  'cup unpacked',
  'cup unsifted',
  'cup whole',
  'dash',
  'dashe',
  'date',
  'disc',
  'dollop',
  'dozen',
  'drink box',
  'drop',
  'dropper',
  'duck',
  'ear',
  'ear large',
  'ear medium',
  'ear small',
  'egg',
  'eggplant',
  'enchilada',
  'envelope',
  'extra large',
  'extra small',
  'fig',
  'filet',
  'fillet',
  'floret',
  'flower',
  'floweret',
  'fluid ounce',
  'fruit',
  'fruit yield',
  'fun size',
  'g',
  'gallon',
  'giblet',
  'glass',
  'glug',
  'grape',
  'guinea',
  'gumdrop',
  'gummy bear',
  'gummy dinosaur',
  'gummy fish',
  'gummy worm',
  'half',
  'half carton',
  'half pint',
  'halve',
  'handful',
  'head',
  'head large',
  'head medium',
  'head small',
  'heart',
  'honeydew ball',
  'inch',
  'individual',
  'individual loaf',
  'jar',
  'jelly ring',
  'jumbo',
  'kernel',
  'kidney',
  'king size',
  'knob',
  'ladyfinger',
  'large',
  'large Gherkin',
  'large bagel',
  'large head',
  'large whole',
  'largehead',
  'leaf inner',
  'leaf outer',
  'leave',
  'leek',
  'leg',
  'lemon yield',
  'lime yield',
  'link',
  'link cooked',
  'liter',
  'liver',
  'loaf',
  'loave',
  'lobster',
  'matzo',
  'medium',
  'medium bagel',
  'medium head',
  'medium whole',
  'melon',
  'midget Gherkin',
  'milliliter',
  'mini',
  'mini bag',
  'mini bagel',
  'miniature',
  'miniature box',
  'miniature boxe',
  'muffin',
  'mushroom',
  'nest',
  'nut',
  'olive',
  'onion',
  'ounce',
  'oz',
  'oz boneles',
  'oz cooked',
  'oz crumbled',
  'pack',
  'package',
  'packet',
  'pancake',
  'pastry',
  'pat',
  'pattie',
  'patty',
  'pea pod',
  'peanut',
  'pepper',
  'peppercorn',
  'pheasant',
  'pie crust',
  'piece',
  'piece whole',
  'pimiento',
  'pinch',
  'pinche',
  'pint',
  'pita',
  'pkt',
  'plum tomato',
  'pod',
  'pomegranate',
  'portion',
  'potato large',
  'potato medium',
  'potato small',
  'pouch',
  'pouche',
  'pound',
  'prepared',
  'prune',
  'puche',
  'quail',
  'quantity',
  'quart',
  'rack',
  'radish',
  'rasher',
  'raspberrie',
  'raw gizzard',
  'raw liver',
  'raw pr g',
  'recipe',
  'recipe yield',
  'regular',
  'rib',
  'ring',
  'roast',
  'roll',
  'root',
  'round',
  'round waffle',
  'sachet',
  'sandwich',
  'sardine',
  'satchet',
  'sausage',
  'scape',
  'scoop',
  'serving',
  'serving packet',
  'sheet',
  'sheet dough',
  'shell',
  'shoot',
  'shot',
  'slab',
  'slice',
  'slice or wedge',
  'slice raw',
  'slice round',
  'slice thin',
  'small',
  'small Gherkin',
  'small bagel',
  'small box',
  'small boxe',
  'small head',
  'small whole',
  'smallhead',
  'snack bag',
  'snack size bag',
  'spear',
  'spear Gherkin',
  'spear tip',
  'spice drop',
  'spice stick',
  'splash',
  'spoonful',
  'spray',
  'sprig',
  'sprout',
  'squab',
  'square',
  'squash',
  'stalk',
  'steak',
  'stem',
  'stick',
  'strand',
  'strip',
  'strip large',
  'strip medium',
  'sweetpotato',
  'tablespoon',
  'taco',
  'tbsp chopped',
  'tbsp creamy',
  'tbsp unsifted',
  'tbsp whipped',
  'teaspoon',
  'thigh with skin',
  'thin slice',
  'thread',
  'tin',
  'tomato',
  'tortilla',
  'tortilla medium',
  'tray',
  'tsp brownulated',
  'tsp chopped',
  'tsp packed',
  'tsp unpacked',
  'tub',
  'tube',
  'tube cake',
  'twist',
  'unit',
  'wafer',
  'waffle',
  'waterchestnut',
  'wedge',
  'wedge or slice',
  'wedge yield',
  'wing',
  'wrapper',
] as const;

export type Ingredient = typeof INGREDIENTS[number];
export type Unit = typeof UNITS[number];
